version: '3.8'

services:

  developers-db:
    image: postgres:alpine3.18
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - my-network
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql:/docker-entrypoint-initdb.d

  developers-webserver:
    image: tomcat:jdk11
    restart: always
    networks:
      - my-network
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ../target/war-file:/usr/local/tomcat/webapps/
      - ./logs:/opt/DeveloperApi/

networks:
  my-network:
    driver: bridge
